-- script to drop views
drop view if exists perf_year1;
drop view if exists perf_year2;
drop view if exists perf_year3;
drop view if exists perf_year4;
drop view if exists perf_year5;
drop view if exists perf_year6;
drop view if exists perf_year7;
drop view if exists perf_year8;
drop view if exists perf_year9;
drop view if exists perf_year10;
